baseURL = 'https://antellezr.github.io/'
languageCode = 'en-us'
title = 'Angel Tellez Portfolio'
theme = 'hugo-book'

# Needed for shortcodes
[markup]
[markup.goldmark.renderer]
unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "tango"
    tabWidth = 4
[params]
  BookSection = "menu"  # Forces Hugo-book to use only "content/menu/"
  BookMenuBundle = "menu" # Limits the sidebar to the menu bundle

